# FRP Freedom Configuration File
# This file contains default settings for the FRP Freedom application

# Application Settings
app:
  version: "1.0.0"
  name: "FRP Freedom"
  debug_mode: false
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  data_directory: "./data"
  temp_directory: "./temp"

# Security and Ethics Settings
security:
  # Ownership verification requirements
  ownership_verification_required: true
  ownership_verification_timeout: 300  # seconds
  
  # Audit trail settings
  audit_trail_enabled: true
  audit_log_retention_days: 90
  
  # Log encryption
  log_encryption_enabled: true
  log_encryption_algorithm: "AES-256-GCM"
  
  # Rate limiting to prevent abuse
  rate_limiting_enabled: true
  max_attempts_per_hour: 5
  max_attempts_per_day: 20
  
  # Session management
  session_timeout: 1800  # 30 minutes
  auto_logout_enabled: true

# Device Management Settings
device:
  # Auto-detection settings
  auto_detect_enabled: true
  auto_detect_interval: 5  # seconds
  
  # Connection timeouts
  connection_timeout: 30  # seconds
  command_timeout: 60  # seconds
  
  # Supported connection types
  supported_connections:
    - "adb"
    - "fastboot"
    - "download"
  
  # Device compatibility
  min_android_version: 5.0
  max_android_version: 15.0
  
  # Supported brands (for optimization)
  supported_brands:
    - "samsung"
    - "google"
    - "huawei"
    - "xiaomi"
    - "oneplus"
    - "lg"
    - "sony"
    - "motorola"
    - "htc"
    - "oppo"
    - "vivo"
    - "realme"

# Bypass Method Settings
bypass:
  # Method categories and priorities
  method_categories:
    adb:
      enabled: true
      priority: 1
      timeout: 300  # seconds
    interface:
      enabled: true
      priority: 2
      timeout: 600  # seconds
    system:
      enabled: true
      priority: 3
      timeout: 900  # seconds
      requires_root: true
    hardware:
      enabled: true
      priority: 4
      timeout: 1200  # seconds
      requires_special_tools: true
  
  # Execution settings
  max_concurrent_methods: 1
  retry_failed_methods: true
  max_retries: 2
  
  # Safety settings
  backup_before_modification: true
  verify_after_bypass: true
  
  # Success criteria
  stop_on_first_success: false  # Continue with all methods for data collection

# User Interface Settings
ui:
  # Window settings
  window:
    width: 1024
    height: 768
    min_width: 800
    min_height: 600
    resizable: true
    remember_position: true
    remember_size: true
  
  # Theme settings
  theme:
    name: "default"
    style: "clam"  # ttk theme
    colors:
      primary: "#2196F3"
      secondary: "#FFC107"
      success: "#4CAF50"
      warning: "#FF9800"
      error: "#F44336"
      info: "#2196F3"
  
  # Font settings
  fonts:
    default:
      family: "Arial"
      size: 10
    heading:
      family: "Arial"
      size: 14
      weight: "bold"
    monospace:
      family: "Consolas"
      size: 9
  
  # Progress and feedback
  progress:
    update_interval: 100  # milliseconds
    show_percentage: true
    show_time_remaining: true
  
  # Tooltips
  tooltips:
    enabled: true
    delay: 500  # milliseconds
    wrap_length: 300

# Logging Settings
logging:
  # Log levels for different components
  levels:
    root: "INFO"
    device_manager: "INFO"
    bypass_manager: "INFO"
    gui: "INFO"
    audit: "INFO"
  
  # Log file settings
  files:
    main_log:
      filename: "frp_freedom.log"
      max_size: 10485760  # 10MB
      backup_count: 5
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    audit_log:
      filename: "audit.log"
      max_size: 52428800  # 50MB
      backup_count: 10
      format: "%(asctime)s - AUDIT - %(message)s"
      encrypted: true
  
  # Console logging
  console:
    enabled: true
    level: "INFO"
    format: "%(levelname)s: %(message)s"

# Network Settings (for future features)
network:
  # API endpoints (if needed)
  api:
    enabled: false
    base_url: "https://api.frp-freedom.org"
    timeout: 30
    verify_ssl: true
  
  # Update checking
  updates:
    check_enabled: true
    check_interval: 86400  # 24 hours
    auto_download: false
    notify_user: true

# Backup and Recovery Settings
backup:
  # Automatic backups
  auto_backup_enabled: true
  backup_location: "./backups"
  
  # Backup retention
  max_backups: 10
  backup_compression: true
  
  # What to backup
  include:
    - "device_info"
    - "method_results"
    - "execution_logs"
    - "verification_data"

# Performance Settings
performance:
  # Memory management
  max_memory_usage: 512  # MB
  garbage_collection_interval: 300  # seconds
  
  # Threading
  max_worker_threads: 4
  thread_pool_size: 8
  
  # Caching
  cache_enabled: true
  cache_size: 100  # MB
  cache_ttl: 3600  # seconds

# Development and Testing Settings
development:
  # Debug features
  debug_mode: false
  verbose_logging: false
  
  # Testing
  mock_devices: false
  simulate_failures: false
  
  # Profiling
  enable_profiling: false
  profile_output: "./profiles"

# Legal and Compliance Settings
legal:
  # Terms and conditions
  terms_version: "1.0"
  require_acceptance: true
  
  # Privacy settings
  data_collection_enabled: false
  analytics_enabled: false
  
  # Compliance
  gdpr_compliance: true
  data_retention_days: 30
  
  # Disclaimers
  show_legal_warnings: true
  require_ownership_confirmation: true

# Experimental Features (disabled by default)
experimental:
  # New bypass methods
  experimental_methods: false
  
  # Advanced features
  batch_processing: false
  remote_execution: false
  
  # AI-powered features
  ai_method_selection: false
  predictive_analysis: false